apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: give-everyone-permissions
subjects:
- kind: Group
  name: system:authenticated  # This binds the role to all authenticated users
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin  # The name of the ClusterRole created in Step 1
  apiGroup: rbac.authorization.k8s.io
