apiVersion: v1
kind: Service
metadata:
  name: youtube-login-app-service
spec:
  selector:
    app: youtube-login-app  
  ports:
    - protocol: TCP
      port: 80         # Service port (to expose externally)
      targetPort: 2020  # Updated target port inside the container
      nodePort: 30056   # External port for NodePort
  type: NodePort
