apiVersion: v1
kind: Service
metadata:
  name: youtube-login-app-service
spec:
  selector:
    app: youtube-login-app  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30056
  type: NodePort
